### ISSUE TITLE
Error getting config

### ISSUE THREAD

**Issue by svor** [nodeshift-starters/nodejs-configmap#180] opened 2021-06-25 09:41 UTC
I see error messages on OpenShift cluster:
```
Environment:
	DEV_MODE=false
	NODE_ENV=production
	DEBUG_PORT=5858
Launching via npm...
npm info it worked if it ends with ok
npm info using npm@6.14.11
npm info using node@v14.16.0
npm info lifecycle nodejs-configmap@4.0.0~prestart: nodejs-configmap@4.0.0
npm info lifecycle nodejs-configmap@4.0.0~start: nodejs-configmap@4.0.0

> nodejs-configmap@4.0.0 start /opt/app-root/src
> node .

[1624613546162] INFO (23 on nodejs-configmap-1-r476c): Listening on port 8080
{"level":50,"time":1624613548135,"pid":23,"hostname":"nodejs-configmap-1-r476c","msg":"Error getting config"}
{"level":50,"time":1624613550133,"pid":23,"hostname":"nodejs-configmap-1-r476c","msg":"Error getting config"}
{"level":50,"time":1624613552134,"pid":23,"hostname":"nodejs-configmap-1-r476c","msg":"Error getting config"}
{"level":50,"time":1624613554134,"pid":23,"hostname":"nodejs-configmap-1-r476c","msg":"Error getting config"}
{"level":50,"time":1624613556135,"pid":23,"hostname":"nodejs-configmap-1-r476c","msg":"Error getting config"}
```

Steps to reproduce:
1. Clone the progect
2. Run npm install
3. Login to OpenShift cluster 4.6 by oc login command 
4. Create a new project `oc new-project my-example-project`
5. oc create configmap app-config --from-file=app-config.yml
6. npm run openshift
7. Go to OpenShift console and check logs in running Pod nodejs-configmap-..

**Comment by lholmquist** [comment] 2021-06-29 17:41
i was able to reproduce.  looking at what the issue is

**Comment by lholmquist** [comment] 2021-06-29 17:53
I just pushed a fix

**Closed as completed** 2021-06-29 17:52 UTC
